// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Data;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("Persistence.Models.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HolderId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HolderId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Persistence.Models.AccountHolder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar");

                    b.Property<string>("BSN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("AccountHolders");
                });

            modelBuilder.Entity("Persistence.Models.IBANStore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("byte");

                    b.HasKey("Id");

                    b.ToTable("IbanStores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = "8261521222",
                            IBAN = "NL21ABNA8261521222",
                            IsActive = false
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = "4883846911",
                            IBAN = "NL18RABO4883846911",
                            IsActive = false
                        },
                        new
                        {
                            Id = 3,
                            AccountNumber = "3767744449",
                            IBAN = "NL35ABNA3767744449",
                            IsActive = false
                        },
                        new
                        {
                            Id = 4,
                            AccountNumber = "1011562413",
                            IBAN = "NL22RABO1011562413",
                            IsActive = false
                        },
                        new
                        {
                            Id = 5,
                            AccountNumber = "5251802137",
                            IBAN = "NL60INGB5251802137",
                            IsActive = false
                        },
                        new
                        {
                            Id = 6,
                            AccountNumber = "4520711568",
                            IBAN = "NL34INGB4520711568",
                            IsActive = false
                        },
                        new
                        {
                            Id = 7,
                            AccountNumber = "1008270121",
                            IBAN = "NL64INGB1008270121",
                            IsActive = false
                        },
                        new
                        {
                            Id = 8,
                            AccountNumber = "3403751775",
                            IBAN = "NL77ABNA3403751775",
                            IsActive = false
                        },
                        new
                        {
                            Id = 9,
                            AccountNumber = "1011562413",
                            IBAN = "NL22RABO1011562413",
                            IsActive = false
                        },
                        new
                        {
                            Id = 10,
                            AccountNumber = "4293946624",
                            IBAN = "NL69ABNA4293946624",
                            IsActive = false
                        },
                        new
                        {
                            Id = 11,
                            AccountNumber = "2682297498",
                            IBAN = "NL11RABO2682297498",
                            IsActive = false
                        },
                        new
                        {
                            Id = 12,
                            AccountNumber = "2067756052",
                            IBAN = "NL62INGB2067756052",
                            IsActive = false
                        },
                        new
                        {
                            Id = 13,
                            AccountNumber = "2859779760",
                            IBAN = "NL55ABNA2859779760",
                            IsActive = false
                        },
                        new
                        {
                            Id = 14,
                            AccountNumber = "5055036109",
                            IBAN = "NL91INGB5055036109",
                            IsActive = false
                        },
                        new
                        {
                            Id = 15,
                            AccountNumber = "9589603858",
                            IBAN = "NL33RABO9589603858",
                            IsActive = false
                        },
                        new
                        {
                            Id = 16,
                            AccountNumber = "8902022560",
                            IBAN = "NL61ABNA8902022560",
                            IsActive = false
                        });
                });

            modelBuilder.Entity("Persistence.Models.TransactionFee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TransactionFees");

                    b.HasData(
                        new
                        {
                            Id = "902d0151-483d-4ada-8320-5346afff69c1",
                            CreateDate = new DateTime(2022, 9, 19, 2, 36, 2, 488, DateTimeKind.Local).AddTicks(5900),
                            ModifyDate = new DateTime(2022, 9, 19, 2, 36, 2, 488, DateTimeKind.Local).AddTicks(5950),
                            Percentage = 1m,
                            Type = 0
                        });
                });

            modelBuilder.Entity("Persistence.Models.TransactionHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountHolderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TransactionHistories");
                });

            modelBuilder.Entity("Persistence.Models.TransactionLimit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaxAmount")
                        .HasMaxLength(18)
                        .HasColumnType("decimal");

                    b.Property<decimal>("MinAmount")
                        .HasMaxLength(18)
                        .HasColumnType("decimal");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TransactionLimits");

                    b.HasData(
                        new
                        {
                            Id = "809b3b27-fd3b-4f5c-a2e4-5ab989744afb",
                            CreateDate = new DateTime(2022, 9, 19, 2, 36, 2, 488, DateTimeKind.Local).AddTicks(7090),
                            MaxAmount = 100m,
                            MinAmount = 1m,
                            ModifyDate = new DateTime(2022, 9, 19, 2, 36, 2, 488, DateTimeKind.Local).AddTicks(7080),
                            Type = 0
                        });
                });

            modelBuilder.Entity("Persistence.Models.Account", b =>
                {
                    b.HasOne("Persistence.Models.AccountHolder", "Holder")
                        .WithMany("Accounts")
                        .HasForeignKey("HolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Holder");
                });

            modelBuilder.Entity("Persistence.Models.AccountHolder", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
